print('hello')
print("2nd line via git cli")
print('3rd line via gui')
print('4th line via git cli')
print('5th line via gui')
print('7th line via cli')
print('6th line via gui')
print('8th line via gui')
print('9th line via cli')
print('editing via cli')
print('10th line via gui')
print('via master branch')
print('editing from another branch')

